-- +goose Up

-- A rider asks for money: from one registered rider (by phone), or from
-- whoever opens its code (a link or a QR code). Paying it is a transfer
-- from the payer to the requester, with the payer's PIN, and closes it.
CREATE TABLE money_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- What the link and the QR code carry.
    code VARCHAR(12) NOT NULL,

    requester_rider_id UUID NOT NULL,
    requester_phone VARCHAR(16) NOT NULL DEFAULT '',

    -- Set when the request is for one rider; for an open request, set to
    -- whoever paid it.
    payer_rider_id UUID NULL,
    payer_phone VARCHAR(16) NULL,
    is_open BOOLEAN NOT NULL DEFAULT false,

    currency_code VARCHAR(3) NOT NULL,
    amount NUMERIC(16, 3) NOT NULL,
    note VARCHAR(140) NOT NULL DEFAULT '',

    status VARCHAR(10) NOT NULL DEFAULT 'pending',
    transfer_id UUID NULL REFERENCES wallet_transfers (id),

    idempotency_key VARCHAR(120) NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT money_requests_code_unique UNIQUE (code),
    CONSTRAINT money_requests_requester_key_unique UNIQUE (requester_rider_id, idempotency_key),

    CONSTRAINT money_requests_amount_positive_check CHECK (amount > 0),
    CONSTRAINT money_requests_status_check
        CHECK (status IN ('pending', 'paid', 'declined', 'cancelled')),
    CONSTRAINT money_requests_payer_check
        CHECK (is_open OR payer_rider_id IS NOT NULL),
    CONSTRAINT money_requests_not_to_self_check
        CHECK (payer_rider_id IS NULL OR payer_rider_id <> requester_rider_id),
    CONSTRAINT money_requests_paid_has_transfer_check
        CHECK (status <> 'paid' OR (transfer_id IS NOT NULL AND payer_rider_id IS NOT NULL))
);

CREATE INDEX money_requests_requester_idx
    ON money_requests (requester_rider_id, created_at DESC);

CREATE INDEX money_requests_payer_idx
    ON money_requests (payer_rider_id, created_at DESC)
    WHERE payer_rider_id IS NOT NULL;

-- What a rider still owes from a cancelled trip's fee is paid off by the
-- next money that reaches their wallet, oldest fee first: due_paid is how
-- much of due_amount is paid.
ALTER TABLE trip_settlements
    ADD COLUMN due_paid NUMERIC(16, 3) NOT NULL DEFAULT 0,
    ADD CONSTRAINT trip_settlements_due_paid_check
        CHECK (due_paid >= 0 AND due_paid <= due_amount);

CREATE INDEX trip_settlements_rider_dues_idx
    ON trip_settlements (rider_id, created_at)
    WHERE due_amount > due_paid;

-- Whether a rider who owes fees may request trips before paying them.
ALTER TABLE wallet_configs
    ADD COLUMN block_trips_with_dues BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE wallet_transactions
    DROP CONSTRAINT IF EXISTS wallet_transactions_type_check;

ALTER TABLE wallet_transactions
    ADD CONSTRAINT wallet_transactions_type_check
        CHECK (
            type IN (
                'top_up',
                'trip_payment',
                'trip_earning',
                'commission',
                'payout',
                'adjustment',
                'change_credit',
                'transfer_out',
                'transfer_in',
                'due_payment'
            )
        );

-- The ledger's order: rows written in one transaction share created_at, so
-- seq says which came first (a credit, then the fee it paid off). It is what
-- a statement's running balance follows.
ALTER TABLE wallet_transactions
    ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX wallet_transactions_wallet_order_idx
    ON wallet_transactions (wallet_id, created_at DESC, seq DESC);

-- +goose Down

DROP INDEX IF EXISTS wallet_transactions_wallet_order_idx;

ALTER TABLE wallet_transactions
    DROP COLUMN IF EXISTS seq;

-- The old constraint has no due_payment: those rows keep their amount and
-- become adjustments.
UPDATE wallet_transactions
SET type = 'adjustment'
WHERE type = 'due_payment';

ALTER TABLE wallet_transactions
    DROP CONSTRAINT IF EXISTS wallet_transactions_type_check;

ALTER TABLE wallet_transactions
    ADD CONSTRAINT wallet_transactions_type_check
        CHECK (
            type IN (
                'top_up',
                'trip_payment',
                'trip_earning',
                'commission',
                'payout',
                'adjustment',
                'change_credit',
                'transfer_out',
                'transfer_in'
            )
        );

ALTER TABLE wallet_configs
    DROP COLUMN IF EXISTS block_trips_with_dues;

DROP INDEX IF EXISTS trip_settlements_rider_dues_idx;

ALTER TABLE trip_settlements
    DROP CONSTRAINT IF EXISTS trip_settlements_due_paid_check,
    DROP COLUMN IF EXISTS due_paid;

DROP TABLE IF EXISTS money_requests;
