-- +goose Up

-- Vouchers: prepaid codes the platform issues in batches and sells through a
-- seller (ZainCash, shops). Staff create a batch (the codes are generated by
-- the service and kept sealed, AES-GCM, until the batch is exported), export
-- it once (the only time the codes leave: code_sealed is wiped), and a rider
-- redeems a code into their wallet. Only an HMAC of each code stays, so a
-- copy of this database redeems nothing.
CREATE TABLE voucher_batches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The start of every serial: V<number>-<index>.
    number BIGINT GENERATED ALWAYS AS IDENTITY,

    label VARCHAR(120) NOT NULL,
    seller VARCHAR(60) NOT NULL DEFAULT '',

    currency_code VARCHAR(3) NOT NULL,
    amount NUMERIC(16, 3) NOT NULL,
    quantity INTEGER NOT NULL,

    status VARCHAR(10) NOT NULL DEFAULT 'created',
    expires_at TIMESTAMPTZ NOT NULL,

    created_by UUID NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    exported_by UUID NULL,
    exported_at TIMESTAMPTZ NULL,

    cancelled_by UUID NULL,
    cancelled_at TIMESTAMPTZ NULL,
    cancel_reason VARCHAR(300) NOT NULL DEFAULT '',

    CONSTRAINT voucher_batches_number_unique UNIQUE (number),
    CONSTRAINT voucher_batches_creator_key_unique UNIQUE (created_by, idempotency_key),

    CONSTRAINT voucher_batches_amount_positive_check CHECK (amount > 0),
    CONSTRAINT voucher_batches_quantity_check CHECK (quantity BETWEEN 1 AND 10000),
    CONSTRAINT voucher_batches_status_check
        CHECK (status IN ('created', 'exported', 'cancelled')),
    CONSTRAINT voucher_batches_exported_check
        CHECK (status <> 'exported' OR exported_at IS NOT NULL),
    CONSTRAINT voucher_batches_cancelled_check
        CHECK (status <> 'cancelled' OR cancelled_at IS NOT NULL)
);

CREATE INDEX voucher_batches_created_idx
    ON voucher_batches (created_at DESC, number DESC);

CREATE TABLE vouchers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    batch_id UUID NOT NULL REFERENCES voucher_batches (id),

    -- Printed next to the code: support finds a voucher by it.
    serial VARCHAR(24) NOT NULL,

    -- HMAC-SHA256 of the normalized code: what a redemption looks up.
    code_hash BYTEA NOT NULL,
    -- The code, sealed, until the batch is exported; NULL after.
    code_sealed BYTEA NULL,

    status VARCHAR(10) NOT NULL DEFAULT 'available',

    redeemed_by_rider_id UUID NULL,
    redeemed_at TIMESTAMPTZ NULL,
    transaction_id UUID NULL REFERENCES wallet_transactions (id),

    voided_by UUID NULL,
    voided_at TIMESTAMPTZ NULL,
    void_reason VARCHAR(300) NOT NULL DEFAULT '',

    CONSTRAINT vouchers_serial_unique UNIQUE (serial),
    CONSTRAINT vouchers_code_hash_unique UNIQUE (code_hash),

    CONSTRAINT vouchers_status_check
        CHECK (status IN ('available', 'redeemed', 'void')),
    CONSTRAINT vouchers_redeemed_check
        CHECK (status <> 'redeemed' OR (redeemed_by_rider_id IS NOT NULL AND redeemed_at IS NOT NULL AND transaction_id IS NOT NULL)),
    CONSTRAINT vouchers_void_check
        CHECK (status <> 'void' OR voided_at IS NOT NULL)
);

CREATE INDEX vouchers_batch_idx ON vouchers (batch_id, serial);

CREATE INDEX vouchers_rider_idx
    ON vouchers (redeemed_by_rider_id, redeemed_at DESC)
    WHERE redeemed_by_rider_id IS NOT NULL;

-- Wrong codes a rider typed: after too many in a while they wait, so codes
-- cannot be guessed by trying.
CREATE TABLE voucher_redeem_failures (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rider_id UUID NOT NULL,
    failed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX voucher_redeem_failures_rider_idx
    ON voucher_redeem_failures (rider_id, failed_at);

ALTER TABLE wallet_transactions
    DROP CONSTRAINT IF EXISTS wallet_transactions_type_check;

ALTER TABLE wallet_transactions
    ADD CONSTRAINT wallet_transactions_type_check
        CHECK (
            type IN (
                'top_up',
                'trip_payment',
                'trip_earning',
                'commission',
                'payout',
                'adjustment',
                'change_credit',
                'transfer_out',
                'transfer_in',
                'due_payment',
                'voucher'
            )
        );

-- +goose Down

-- The old constraint has no voucher: those rows keep their amount and become
-- adjustments.
UPDATE wallet_transactions
SET type = 'adjustment'
WHERE type = 'voucher';

ALTER TABLE wallet_transactions
    DROP CONSTRAINT IF EXISTS wallet_transactions_type_check;

ALTER TABLE wallet_transactions
    ADD CONSTRAINT wallet_transactions_type_check
        CHECK (
            type IN (
                'top_up',
                'trip_payment',
                'trip_earning',
                'commission',
                'payout',
                'adjustment',
                'change_credit',
                'transfer_out',
                'transfer_in',
                'due_payment'
            )
        );

DROP TABLE IF EXISTS voucher_redeem_failures;
DROP TABLE IF EXISTS vouchers;
DROP TABLE IF EXISTS voucher_batches;
